#ifndef _SALSA20_CONSTANTS_
#define _SALSA20_CONSTANTS_

#define NONCEWORDS 2
#define KEYWORDS 8
#define COUNTERWORDS 2
#define NONCEBYTES (NONCEWORDS * 4)
#define KEYBYTES (KEYWORDS * 4)
#define COUNTERBYTES (COUNTERWORDS * 4)
#define BLOCKSIZE 64
#define BLOCKSIZEWORD (BLOCKSIZE/4)


#endif